In [1]:
from Bio.Seq import Seq

In [2]:
my_seq = Seq("AGTACACTGGT");print(my_seq)

AGTACACTGGT


In [3]:
from Bio import SeqIO
for seq_record in SeqIO.parse("ls_orchid.fasta", "fasta"):
    print(seq_record.id)
    print(repr(seq_record.seq))
    print(len(seq_record))

gi|2765658|emb|Z78533.1|CIZ78533
Seq('CGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTGATGAGACCGTGG...CGC', SingleLetterAlphabet())
740
gi|2765657|emb|Z78532.1|CCZ78532
Seq('CGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTGTTGAGACAACAG...GGC', SingleLetterAlphabet())
753
gi|2765656|emb|Z78531.1|CFZ78531
Seq('CGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTGTTGAGACAGCAG...TAA', SingleLetterAlphabet())
748
gi|2765655|emb|Z78530.1|CMZ78530
Seq('CGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTGTTGAAACAACAT...CAT', SingleLetterAlphabet())
744
gi|2765654|emb|Z78529.1|CLZ78529
Seq('ACGGCGAGCTGCCGAAGGACATTGTTGAGACAGCAGAATATACGATTGAGTGAA...AAA', SingleLetterAlphabet())
733
gi|2765652|emb|Z78527.1|CYZ78527
Seq('CGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTGTTGAGACAGTAG...CCC', SingleLetterAlphabet())
718
gi|2765651|emb|Z78526.1|CGZ78526
Seq('CGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTGTTGAGACAGTAG...TGT', SingleLetterAlphabet())
730
gi|2765650|emb|Z78525.1|CAZ78525
Seq('TGTTGAGATAGCAGAATATACATCGAGTGAATCCGGAGGACCTGTGGTTATTCG...GC

In [4]:
print(seq_record.seq)
     

CATTGTTGAGATCACATAATAATTGATCGAGTTAATCTGGAGGATCTGTTTACTTTGGTCACCCATGGGCATTTGCTGTTGAAGTGACCTAGATTTGCCATCGAGCCTCCTTGGGAGCTTTCTTGTTGGCGAGATCTAAACCCCTGCCCGGCGGAGTTGGGCGCCAAGTCATATGACACATAATTGGTGAAGGGGGTGGTAATCCTGCCCTGACCCTCCCCAAATTATTTTTTTAACAACTCTCAGCAACGGATATCTCGGCTCTTGCATCGATGAAGAACGCAGCGAAATGCGATAATGGTGTGAATTGCAGAATCCCGTGAACATCGAGTCTTTGAACGCAAGTTGCGCCCGAGGCCATCAGGCCAAGGGCACGCCTGCCTGGGCATTGCGAGTCATATCTCTCCCTTAATGAGGCTGTCCATACATACTGTTCAGCCGGTGCGGATGTGAGTTTGGCCCCTTGTTCTTTGGTACGGGGGGTCTAAGAGCTGCATGGGCTTTGGATGGTCCTAAATACGGAAAGAGGTGGACGAACTATGCTACAACAAAATTGTTGTGCAAATGCCCCGGTTGGCCGTTTAGTTGGGCC


In [5]:
for seq_record in SeqIO.parse("ls_orchid.fasta", "fasta"):
    print(seq_record.seq)

CGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTGATGAGACCGTGGAATAAACGATCGAGTGAATCCGGAGGACCGGTGTACTCAGCTCACCGGGGGCATTGCTCCCGTGGTGACCCTGATTTGTTGTTGGGCCGCCTCGGGAGCGTCCATGGCGGGTTTGAACCTCTAGCCCGGCGCAGTTTGGGCGCCAAGCCATATGAAAGCATCACCGGCGAATGGCATTGTCTTCCCCAAAACCCGGAGCGGCGGCGTGCTGTCGCGTGCCCAATGAATTTTGATGACTCTCGCAAACGGGAATCTTGGCTCTTTGCATCGGATGGAAGGACGCAGCGAAATGCGATAAGTGGTGTGAATTGCAAGATCCCGTGAACCATCGAGTCTTTTGAACGCAAGTTGCGCCCGAGGCCATCAGGCTAAGGGCACGCCTGCTTGGGCGTCGCGCTTCGTCTCTCTCCTGCCAATGCTTGCCCGGCATACAGCCAGGCCGGCGTGGTGCGGATGTGAAAGATTGGCCCCTTGTGCCTAGGTGCGGCGGGTCCAAGAGCTGGTGTTTTGATGGCCCGGAACCCGGCAAGAGGTGGACGGATGCTGGCAGCAGCTGCCGTGCGAATCCCCCATGTTGTCGTGCTTGTCGGACAGGCAGGAGAACCCTTCCGAACCCCAATGGAGGGCGGTTGACCGCCATTCGGATGTGACCCCAGGTCAGGCGGGGGCACCCGCTGAGTTTACGC
CGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTGTTGAGACAACAGAATATATGATCGAGTGAATCTGGAGGACCTGTGGTAACTCAGCTCGTCGTGGCACTGCTTTTGTCGTGACCCTGCTTTGTTGTTGGGCCTCCTCAAGAGCTTTCATGGCAGGTTTGAACTTTAGTACGGTGCAGTTTGCGCCAAGTCATATAAAGCATCACTGATGAATGACATTATTGTCAGAAAAAATCAGAGGGGCAGTATG

In [6]:
from Bio.Seq import Seq
seq1 = Seq("AT");seq2=Seq("ATT")

In [7]:
print(seq1);print(seq2)

AT
ATT


In [8]:
from Bio import pairwise2
from Bio.pairwise2 import format_alignment
alignments = pairwise2.align.globalxx(seq1, seq2);##Needleman-Wunsch Algorithm
for a in alignments:
    print(format_alignment(*a))

AT-
|||
ATT
  Score=2

A-T
|||
ATT
  Score=2



In [9]:
print(alignments)

[('AT-', 'ATT', 2.0, 0, 3), ('A-T', 'ATT', 2.0, 0, 3)]


In [10]:
alignments = pairwise2.align.localxx(seq1, seq2)##Smith-Waterman Algorithm

# Use format_alignment method to format the alignments in the list
for b in alignments:
    print(format_alignment(*b))

A-T
|||
ATT
  Score=2

AT-
||
ATT
  Score=2



In [11]:
# match score(eg:A_A) is 2,mismatch score (A_T) is -1, gap open score is -0.5,gap extension is -0.1
alignments = pairwise2.align.globalms(X, Y, 2, -1, -0.5, -0.1)

# Use format_alignment method to format the alignments in the list
for c in alignments:
    print(format_alignment(*c))

NameError: name 'X' is not defined

In [12]:
# match score(eg:A_A) is 2,mismatch score (A_T) is -1, gap open score is -0.5,gap extension is -0.1
alignments = pairwise2.align.globalms(seq1, seq2, 2, -1, -0.5, -0.1)

# Use format_alignment method to format the alignments in the list
for c in alignments:
    print(format_alignment(*c))

AT-
|||
ATT
  Score=3.5

A-T
|||
ATT
  Score=3.5



In [13]:
# match score(eg:A_A) is 2,mismatch score (A_T) is -1, gap open score is -0.5,gap extension is -0.1
alignments = pairwise2.align.localxx(seq1, seq2, 2, -1, -0.5, -0.1)

# Use format_alignment method to format the alignments in the list
for d in alignments:
    print(format_alignment(*d))

TypeError: localxx takes exactly 2 argument (6 given)

In [14]:
###summary global alignemnt and local alignment, the former one could set multiple arguments, the latter couldn't.
from Bio.Seq import Seq
from Bio import pairwise2
from Bio.pairwise2 import format_alignment
seq1 = Seq("AT");seq2=Seq("ATT")
alignments1 = pairwise2.align.globalxx(seq1, seq2);##Needleman-Wunsch Algorithm
alignments2 = pairwise2.align.localxx(seq1, seq2)##Smith-Waterman Algorithm
alignments3 = pairwise2.align.globalms(seq1, seq2, 2, -1, -0.5, -0.1)
for a in alignments1:
    print(format_alignment(*a))
for b in alignments2:
    print(format_alignment(*b))
for c in alignments3:
    print(format_alignment(*c))

AT-
|||
ATT
  Score=2

A-T
|||
ATT
  Score=2

A-T
|||
ATT
  Score=2

AT-
||
ATT
  Score=2

AT-
|||
ATT
  Score=3.5

A-T
|||
ATT
  Score=3.5



In [15]:
Homo = Seq("GTCTACGGCCATACCACCCTGAAA");Candida=Seq("GGTTGCGGCCATATCTAGCAGAAA")
alignments1 = pairwise2.align.globalxx(Homo, Candida);##Needleman-Wunsch Algorithm
for a in alignments1:
    print(format_alignment(*a))###show out all the possible global alignments with the maximum similarity score

G-TCTA-CGGCCATAC-C-ACC-CT-GAAA
||||||||||||||||||||||||||||||
GGT-T-GCGGCCATA-TCTA--GC-AGAAA
  Score=18

-GTCTA-CGGCCATAC-C-ACC-CT-GAAA
||||||||||||||||||||||||||||||
GGT-T-GCGGCCATA-TCTA--GC-AGAAA
  Score=18

G-TCTACGGCCATAC-C-ACC-CT-GAAA
|||||||||||||||||||||||||||||
GGT-TGCGGCCATA-TCTA--GC-AGAAA
  Score=18

-GTCTACGGCCATAC-C-ACC-CT-GAAA
|||||||||||||||||||||||||||||
GGT-TGCGGCCATA-TCTA--GC-AGAAA
  Score=18

G-TCTA-CGGCCATACC-ACC-CT-GAAA
|||||||||||||||||||||||||||||
GGT-T-GCGGCCATATCTA--GC-AGAAA
  Score=18

-GTCTA-CGGCCATACC-ACC-CT-GAAA
|||||||||||||||||||||||||||||
GGT-T-GCGGCCATATCTA--GC-AGAAA
  Score=18

G-TCTACGGCCATACC-ACC-CT-GAAA
||||||||||||||||||||||||||||
GGT-TGCGGCCATATCTA--GC-AGAAA
  Score=18

-GTCTACGGCCATACC-ACC-CT-GAAA
||||||||||||||||||||||||||||
GGT-TGCGGCCATATCTA--GC-AGAAA
  Score=18

G-TCTA-CGGCCATA-CC-ACC-CT-GAAA
||||||||||||||||||||||||||||||
GGT-T-GCGGCCATATC-TA--GC-AGAAA
  Score=18

-GTCTA-CGGCCATA-CC-ACC-CT-GAAA
||||||||||||||||||||||||||||||
GGT-T-GCGGCCATATC

In [16]:
alignments3 = pairwise2.align.globalms(Homo, Candida, 2, -1, -0.5, -0.1);
for c in alignments3:
    print(format_alignment(*c))###after giving a new scoring scheme, possible outcomes become less

G-TCTA-CGGCCATA-C---CACCCTGAAA
||||||||||||||||||||||||||||||
GGT-T-GCGGCCATATCTAGCA----GAAA
  Score=32

-GTCTA-CGGCCATA-C---CACCCTGAAA
||||||||||||||||||||||||||||||
GGT-T-GCGGCCATATCTAGCA----GAAA
  Score=32

G-TCTACGGCCATA-C---CACCCTGAAA
|||||||||||||||||||||||||||||
GGT-TGCGGCCATATCTAGCA----GAAA
  Score=32

-GTCTACGGCCATA-C---CACCCTGAAA
|||||||||||||||||||||||||||||
GGT-TGCGGCCATATCTAGCA----GAAA
  Score=32



In [17]:
## a little discovery:

In [18]:
## Global alignment and local alignment do not use information about the sites, like transition probability from one to another nuclotide. 
## Consider the forward and backward sample in pairhmm by R programming example, they provide a more informative solution.

In [ ]:
## Could I try to use same idea in pairhmm to align two sequences in Python codes? Practice Python!

In [5]:
def tonumber(letters):
    Dic={'A':1,'T':2,'G':3,'C':4}
    aa=[]
    for i in list(letters):
        aa.append(Dic[i])
    return(aa)

In [6]:
from Bio.Seq import Seq
tonumber(Seq("AATTGC"))

[1, 1, 2, 2, 3, 4]

In [33]:
def wrap0(x,b):
    x=x % (2*b)
    if x>b:
        x=2*b-x
    return(x)
def wrap(x,a,b):
    return(a+wrap0(x-a,b-a))
def showone(letters,path,S):
    row=[]
    x=0
    for i in range(len(path)):
        if path[i]==S:
            row.append('-')
        else:
            row.append(letters[x])
            x=x+1
    return(row)
def draw(letters1,letters2,path):
    print(showone(letters1,path,I))    
    print(showone(letters2,path,D))

In [8]:
from numpy import *
import random
from __future__ import division 
def choose(pr):
    pr=pr/sum(pr)
    u=random.uniform(0, 1)
    total=0.0
    for i in range(len(pr)):
        total=total+pr[i]
        s=i+1
        if u< total:
            break
    return(s)

In [9]:
M = 1
D = 2 # + -
I = 3 # - +
S = 4
E = 5

In [10]:
import numpy
def pairhmm(d,e):
    x1 = numpy.array((1-2*d, d, d, 0, 1))
    x2 = numpy.array(((1-e)*(1-2*d), e + (1-e)*d, (1-e)*d, 0, 1))
    x3 = numpy.array(((1-e)*(1-2*d), (1-e)*d, e + (1-e)*d, 0, 1))
    x= numpy.array((x1, x2, x3))
    return(x)
Q= numpy.array([[-3,1,1,1],[1,-3,1,1],[1,1,-3,1],[1,1,1,-3]])/3

In [11]:
def totalprob(FM):
    XX=FM.shape[1]-1
    YY=FM.shape[2]-1
    return(FM[0,XX,YY] + FM[1,XX,YY] + FM[2,XX,YY])

In [22]:
def backsample(FM,T):
    X=FM.shape[1]
    Y=FM.shape[2]
    x=X
    y=Y
    s=E
    states=[]
    while x>1 or y>1:
        s=choose(FM[:,x-1,y-1]*T[:,s-1])
        states.append(s)
        if s == 1:
            x=x-1
            y=y-1
        elif s == 2:
            x=x-1
        elif s == 3:
            y=y-1
        else:
            print("hello world")
    return(states)

In [13]:
import math
t=0.25
d=0.05
e=0.5
P=power(math.e,Q*t)-(ones((4,4))-eye(4))
pi=[0.25,0.25,0.25,0.25]

In [10]:
def forwardmatrix(seq1,seq2,T,P,pi):
    X=1+len(seq1)
    Y=1+len(seq2)
    FM=numpy.zeros((3,X,Y))
    FM[0,0,0] = 1
    for x in range(1,X+1):
        for y in range(1,Y+1):
            lx=seq1[x-2]
            ly=seq2[y-2]
            if x>1 and y>1:
                x2=x-2
                y2=y-2
                FM[0,x-1,y-1]=FM[0,x2,y2]*T[0,0]+FM[1,x2,y2]*T[1,0]+FM[2,x2,y2]*T[2,0]
                FM[0,x-1,y-1]=FM[0,x-1,y-1]*pi[lx]*P[lx,ly]
            if x>1:
                x2=x-2
                y2=y-1
                FM[1,x-1,y-1]=FM[0,x2,y2]*T[0,1]+FM[1,x2,y2]*T[1,1]+FM[2,x2,y2]*T[2,1]
                FM[1,x-1,y-1]=FM[1,x-1,y-1]*pi[lx]
            if y>1:
                x2=x-1
                y2=y-2
                FM[2,x-1,y-1]=FM[0,x2,y2]*T[0,2]+FM[1,x2,y2]*T[1,2]+FM[2,x2,y2]*T[2,2]
                FM[2,x-1,y-1]=FM[2,x-1,y-1]*pi[ly]
            else:
                pass
    return(FM)

In [11]:
###IndexError: list index out of range

In [12]:
### one intersting discovery: Python and R results are slightly different when computing the exponential of square matrix
### please look at the fllowing cell:

In [13]:
import math
pythonres=power(math.e,eye(3))
Rres=math.e*(eye(3))####in R use expm(diag(3))
print(pythonres-Rres)
testPy=power(math.e,Q*t)
testR=0.07086717*(ones((4,4)))+0.71653131*eye(4)##rewrite from R result
print(testPy-testR)

[[ 0.  1.  1.]
 [ 1.  0.  1.]
 [ 1.  1.  0.]]
[[-0.0085977   1.01603688  1.01603688  1.01603688]
 [ 1.01603688 -0.0085977   1.01603688  1.01603688]
 [ 1.01603688  1.01603688 -0.0085977   1.01603688]
 [ 1.01603688  1.01603688  1.01603688 -0.0085977 ]]


In [1]:
###Therefore, my suppose is that python maybe make a little mistake when facing this task, namely,
### Python use ones instead of eye as the first term in taylor expansion of e^A.

In [14]:
########################### learn from peer ###########################
def forwardmatrix(seq1,seq2,T,P,pi):
    '''
    input
        seq1:
        seq2:
        T:
        P:
        pi:
    output
        
    '''
    X=1+len(seq1)
    Y=1+len(seq2)
    FM=numpy.zeros((3,X,Y))
    FM[0,0,0] = 1
    for x in range(1,X+1):
        for y in range(1,Y+1):
            lx = seq1[x-2] #
            ly = seq2[y-2] # Will you get seq1-value from ndex [-1]i,[0] to [X-1]?
            if x>1 and y>1:
                x2=x-2
                y2=y-2
                FM[0,x-1,y-1] = FM[0,x2,y2]*T[0,0]+FM[1,x2,y2]*T[1,0]+FM[2,x2,y2]*T[2,0]
                FM[0,x-1,y-1] = FM[0,x-1,y-1]*pi[lx-1]*P[lx-1,ly-1] #The size of P is (4, 4), if lx==4, then the same error will be thrown out.
            if x>1:
                x2=x-2
                y2=y-1
                FM[1,x-1,y-1]=FM[0,x2,y2]*T[0,1]+FM[1,x2,y2]*T[1,1]+FM[2,x2,y2]*T[2,1]
                FM[1,x-1,y-1]=FM[1,x-1,y-1]*pi[lx-1]
            if y>1:
                x2=x-1
                y2=y-2
                FM[2,x-1,y-1]=FM[0,x2,y2]*T[0,2]+FM[1,x2,y2]*T[1,2]+FM[2,x2,y2]*T[2,2]
                FM[2,x-1,y-1]=FM[2,x-1,y-1]*pi[ly-1] #With ly=seq2[y-2], if ly=4 on y=3, then pi[4] will be throw out "error of list out of range!" with len(pi) = 4. 
            else:
                pass
    return FM

In [38]:
from Bio.Seq import Seq
seq1 = tonumber(Seq("AT"));
seq2 = tonumber(Seq("ATT"));
FM = forwardmatrix(seq1, seq2, pairhmm(d,e), P,pi)
path = backsample(FM,pairhmm(d,e))
draw(list(Seq("AT")),list(Seq("ATT")),path)

['A', '-', 'T']
['A', 'T', 'T']


In [39]:
####great! fly away###

In [40]:
from Bio.Seq import Seq
seq1 = tonumber(Seq("GTCTACGGCCATACCACCCTGAAA"));
seq2 = tonumber(Seq("GGTTGCGGCCATATCTAGCAGAAA"));
FM = forwardmatrix(seq1, seq2, pairhmm(d,e), P,pi)
path = backsample(FM,pairhmm(d,e))
draw(list(Seq("GTCTACGGCCATACCACCCTGAAA")),list(Seq("GGTTGCGGCCATATCTAGCAGAAA")),path)

['G', 'T', 'C', 'T', 'A', 'C', 'G', 'G', 'C', 'C', 'A', 'T', 'A', 'C', 'C', 'A', 'C', 'C', 'C', 'T', 'G', 'A', 'A', 'A']
['G', 'G', 'T', 'T', 'G', 'C', 'G', 'G', 'C', 'C', 'A', 'T', 'A', 'T', 'C', 'T', 'A', 'G', 'C', 'A', 'G', 'A', 'A', 'A']


In [41]:
####great! fly away###